name: digital_communications
channels:
  - plotly
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - python=3.8.18
  - anyio=4.2.0
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - asttokens=2.0.5
  - async-lru=2.0.4
  - attrs=23.1.0
  - babel=2.11.0
  - backcall=0.2.0
  - beautifulsoup4=4.12.2
  - blas=1.0
  - bleach=4.1.0
  - bottleneck=1.3.7
  - brotli=1.0.9
  - ca-certificates=2023.12.12
  - certifi=2024.2.2
  - cffi=1.16.0
  - charset-normalizer=2.0.4
  - click=8.1.7
  - colorama=0.4.6
  - cycler=0.11.0
  - dash=2.15.0
  - dash-bootstrap-components=1.5.0
  - debugpy=1.6.7
  - decorator=5.1.1
  - defusedxml=0.7.1
  - flask=2.2.5
  - fonttools=4.25.0
  - h11=0.14.0
  - httpcore=1.0.2
  - httpx=0.26.0
  - icu=73.1
  - idna=3.4
  - importlib-metadata=7.0.1
  - ipykernel=6.28.0
  - ipython=8.12.2
  - itsdangerous=2.0.1
  - jedi=0.18.1
  - jinja2=3.1.3
  - json5=0.9.6
  - jsonschema=4.19.2
  - jupyter_client=8.6.0
  - jupyter_core=5.5.0
  - jupyter_server=2.10.0
  - jupyterlab=4.1.1
  - matplotlib=3.5.3
  - nb_conda_kernels=2.3.1
  - notebook=7.1.0
  - numpy=1.24.3
  - pandas=1.5.3
  - plotly=5.18.0
  - scipy=1.10.1
  - pip:
    - jupyter-book
